### PR TITLE
(Update) Adopt PHP PSR-2 Coding Style + Adopt PHP Short Array Syntax

### PR DESCRIPTION
**Pull request by HDVinnie**
- WIP

Aiming to modernize codebase just a tad.

### CODE REVIEW

**Comment by HDVinnie** [comment]
@imtiazmahbub whats your opinion on this?

**Comment by imtiazmahbub** [comment]
Hi HV! Thanks a bunch for the PR
I'll review it and reply back promptly.

**Comment by jeanmarieclement** [comment]
Hi @HDVinnie , thanks for your job and interest on modernize xbtit, I didn't read every single lines you've changed, they're too much! The only thing you must keep in mind is that the script should always work on all hosting services (VPS, dedicated or shared) with PHP > 5.4 AND mySQL > 5

**Comment by HDVinnie** [comment]
@jeanmarieclement these changes do not break that.

However is there a reason you want to support PHP 5.4 + and not PHP 7+ only. PHP 5.4 is at end of life next month.
https://secure.php.net/supported-versions.php

Also plan to make in another PR so XBTIT is MySQL 5.7 + or MariaDB 10.2 + strict mode ready.

As for hosting. This of course doesn't effect that in anyway.

**Comment by jeanmarieclement** [comment]
@HDVinnie yes, the mean reason is that not all hosting providers provide PHP 7, we always try to keep xbtit  working "on every host" as possible, so unless all hosting offer PHP 7, I suggest to keep compatibility with PHP 5.6 too

**Comment by HDVinnie** [comment]
@jeanmarieclement I hear you. However I would hope any reputable host would offer PHP 7+ by now. However this PR doesn't break PHP 5.6 support and will keep in mind that future ones don't if thats what you guys truly want. Just keep in mind PHP 5.4 is at end of life next month. Thus will be supporting a dead PHP version.

**Comment by imtiazmahbub** [comment]
Talking from my experience with hosting:
Most of the webhosts offer PHP lowest version 5.6
And in recent years, it's really easy to manage multiple PHP versions. If someone owns a VPS, if PHP latest version wasn't shipped with the default configuration, he can install what's needed.

**Comment by HDVinnie** [comment]
So how you guys feeling on this? If merged I can start working on https://github.com/btiteam/xbtit/issues/62.

**Pull request merged**
